version: 0.{build}
skip_tags: true
cache: C:\Users\appveyor\AppData\Local\NuGet\Cache
build_script:
- git submodule update --init --recursive
- scripts\make.bat
test: off
artifacts:
- path: output/*
  name: lifecycle
deploy:
- provider: S3
  access_key_id: AKIAI2AAY3LUVTHYDTDA
  secret_access_key:
    secure: zNBMp5HGSOJLlSY+lBKwgWH5eE71tYCWST8QQjXO+IwIE2pDeI/uv5Nm0iBwob4K
  region: us-east-1
  bucket: build-windows-app-lifecycle
  artifact: lifecycle
  set_public: true
  on:
    branch: master
branches:
  only:
  - master
  - /appveyor/
